source 'https://gems.ruby-china.com'
gem 'rails', '5.1.4'

gem 'puma', '3.12.2'
gem 'sass-rails', '5.0.6'
gem 'uglifier', '3.2.0'
gem 'coffee-rails', '4.2.2'
gem 'jquery-rails', '4.3.1'
gem 'turbolinks', '5.0.1'
gem 'jbuilder', '2.7.0'
gem 'bootstrap-sass', '3.4.1'
gem 'sassc-rails', '>= 2.1.0'
gem 'will_paginate', '3.1.6'
gem 'uuid',  '2.3.9'
# gem 'rseg', '~> 0.1.7'
# gem 'autoprefixer-rails'
# gem 'rseg_harry', '~> 0.0.4'
gem 'jieba_rb', '~> 0.0.5'

# gem 'rmmseg', '0.1.6'
# gem 'elasticsearch-model', '7.0.0'
# gem 'elasticsearch-rails', '7.0.0'


# gem 'bootstrap-will_paginate', '1.0.0'
#gem "therubyracer"

# gem 'nodejs-rails', '~> 0.0.1'
# gem 'therubyracer', '~> 0.12.3'
# gem "less-rails"
# gem "twitter-bootstrap-rails"

group :development, :test do
gem 'sqlite3', '1.3.13'

# gem 'byebug', '9.0.6', platform: :mri
end
group :development do
gem 'web-console', '3.5.1'
gem 'listen', '3.0.8'
gem 'spring', '2.0.2'
gem 'spring-watcher-listen', '2.0.1'
end
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]